server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: 1MS08is095@
  application:
    name: USER-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8085